version: '3.3'

services:
  app:
    build: .
    command: python manage.py test
    expose:
      - 8000
    env_file:
      - ./YandexSchool/.env
    depends_on:
      - db
  db:
    image: postgres:12
    expose:
      - 5432
    volumes:
      - ../pg_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=yandex_rest
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata