# Generated by Django 3.1.7 on 2021-03-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_id',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Идентификатор курьера'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='courier_type',
            field=models.CharField(choices=[('foot', 'Пеший курьер'), ('bike', 'Велокурьер'), ('car', 'Курьер на автомобиле')], max_length=4, verbose_name='Тип курьера'),
        ),
    ]
