# Generated by Django 3.1.7 on 2021-03-19 14:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), size=None, verbose_name='Промежутки приёма заказов'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Идентификатор заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новый'), (1, 'В работе'), (2, 'Завершённый')], default=0, verbose_name='Вес заказа'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='courier_type',
            field=models.IntegerField(choices=[('foot', 'Пеший курьер'), ('bike', 'Велокурьер'), ('car', 'Курьер на автомобиле')], verbose_name='Тип курьера исполняющего заказ'),
        ),
    ]
